name: Keep Alive

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl https://fivrrchatbot.onrender.com/health
